name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: yarn
    - name: Type Check
      run: yarn tsc
    - name: Lint
      run: yarn lint
